language: generic 
sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t skm/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true skm/docker-react npm run test